CLASS_NAMES: [  'plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

MODEL:
  NAME: VGG
  LAYER: [64, 'M', 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512, 'M']
  RESUME: False
  
LOSS: 
  FUNCTION: CrossEntropyLoss

OPTIMIZATION:
  OPTIMIZER: SGD
  LR: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  SCHEDULER: CosineAnnealingLR

