CLASS_NAMES: [  'plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

MODEL:
  NAME: VGG
  LAYER: [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 'M', 512, 512, 512, 'M', 512, 512, 512, 'M']
  RESUME: False
  LOSS_CONFIG: CrossEntropyLoss

OPTIMIZATION:
  BATCH_SIZE: 128
  TEST_BATCH_SIZE: 100
  NUM_EPOCHS: 200
  OPTIMIZER: SGD
  LR: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  SCHEDULER: CosineAnnealingLR
